### ISSUE TITLE
Random effects for individuals ?

### ISSUE THREAD

**Issue by Harithaa-Anandakumar** [bryandmartin/corncob#111]
Dear Bryan, 

Thank you for this great package!! 

As far as I understand, there is no possibility to add random effects (for individuals measured over different time points) in the current version of `corncob`. 

Is there a way I can add this or do you have any recommendations? 

Thanks!

**Comment by bryandmartin** [comment]
Hi @Harithaa-Anandakumar ,

As of right now, random effects are not implemented in corncob. Depending on the details of your experimental design, my current recommendation if you want to control for an individual effect is to use something like a fixed effect for individual. 

Adding this is something I want to do eventually, but it is a pretty major task. To be honest, it will be some time before this gets implemented. Still, I think with most experimental designs you can still construct a perfectly valid design matrix to capture your set up. I'm happy to talk through your thoughts here if you want!

Bryan

**Comment by Harithaa-Anandakumar** [comment]
Thank you for your response!

I am working with a randomised controlled trial (2 arms/groups - one placebo/one not) and sampled at 2 time points (pre and post intervention). I want to now somehow correct for the correlation within individuals across time. 

So something like: `post ~ pre + group` in a classical setting but (post - bacterial abundance at second time point, pre - at first time point) 

equivalently `bacterial abundance ~ Group + Time Point + (1|Individual) [Random effects for individual] + covariates`.. 

Am not sure how to translate this into corncob.

**Comment by bryandmartin** [comment]
You are very welcome! The translation here would be to use fixed effects for the individual. Then you would have a pre/post covariate as well as an individual covariate. 

There is some discussion on this point in #63 as well that might be helpful to read through as well.

**Comment by Midnighter** [comment]
Just to add my voice; I would find the ability to add random effects and longitudinal ones as mentioned in #63 very helpful.

**Comment by Harithaa-Anandakumar** [comment]
Thank you so much @bryandmartin ! 

I have a follow-up question related to [this question](https://github.com/bryandmartin/corncob/issues/113#issuecomment-806269340). Given that we get these significant models and their coefficients back, what do you suggest to be a good follow-up visualissation/test?

Currently for a model that tests (differential abundance) Group differences (with 2 groups) controlling for time (2 time points), I am doing a cliff's delta value as a measure of effect size and a Wilcox. test for p-value, at time point 1 (grp 1 vs grp 2) and at time point 2 (grp1 vs grp2). And for differential variability I am using Levene's test in a similar setting. 

This I believe is not the way to go, but I am not sure how to somehow show the "biological relevance" from the model?
