### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by NicolasLouw** [bryandmartin/corncob#116]
Good day
Firstly, thanks for making this package available. I think it will be really useful to help me analyze my data. I do however have a problem that might be very simple, but when I try to install the package, it fails to install every time. This is the error message that I get:
"Installing package into ‘/Users/nicolas/Library/R/3.6/library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘phyloseq’ is not available for package ‘corncob’
* removing ‘/Users/nicolas/Library/R/3.6/library/corncob’
Error: Failed to install 'corncob' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_c/xd75n3zj4099y5bc8yp2k_7h0000gn/T//Rtmpe69DOH/file2577377fc7/corncob_0.2.0.tar.gz’ had non-zero exit status"

I have tried installing phyloseq as well, but I still get this error message. If you have any advice on how I can install this package smoothly without any errors, I would kindly appreciate that. 

Best
Nicolas

**Comment by bryandmartin** [comment]
What error message prints out when you run this code?

`source('http://bioconductor.org/biocLite.R')`
`biocLite('phyloseq')`

**Comment by NicolasLouw** [comment]
Hi, thanks for getting back to me. 
I get the following error messages:
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
> biocLite('phyloseq')
Error in biocLite("phyloseq") : could not find function "biocLite"

**Comment by bryandmartin** [comment]
Oh sorry about that, please try the following:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.12")
BiocManager::install(c("phyloseq"))
```
After this is done, try
`install.packages("corncob")`
and let me know what, if any, error persists.

**Comment by NicolasLouw** [comment]
Thank you so much! I ran that code and managed to install and activate corncob. 

Best
Nicolas

**Comment by bryandmartin** [comment]
Great, for posterity purposes and anyone reading this in the future, the problem was that phyloseq was not installed. Installing Bioconductor packages can be a bit finicky, but they update their install instructions on this webpage: https://bioconductor.org/install

Follow the instructions there to first install phyloseq, then corncob should install no problem.
