### ISSUE TITLE
editing bbdml plots

### ISSUE THREAD

**Issue by mtswanson2017** [bryandmartin/corncob#117]
Hi Bryan!

Thank you for developing such an awesome and easy to use package!!!

Sorry to be a bother, but do you know how I can switch which covariate groups the default red and blue colors are applied to? I want to keep the order the samples and groups are presented in but just change which group is red and which is blue. This is just to be consistent with other figures in my manuscript. I've tried editing the source code for plot.bbdml but haven't had luck with anything I've tried.

Thank you again!

**Comment by bryandmartin** [comment]
Hi @mtswanson2017 ,

The plot function actually has a `color` parameter you can use to fully specify the colors. Check out `?corncob:::plot.bbdml` for details! Please let me know if this doesn't address your issue.
