### ISSUE TITLE
differentialTest

### ISSUE THREAD

**Issue by bryandmartin** [bryandmartin/corncob#15]
Want not just that they are significant, but direction / plot of significant taxa.

**Comment by adw96** [comment]
Since they love the taxonomy/phylogeny trays so much, you might want to consider plotting it as labels on the taxonomy.  Therefore, if there are related groups that consistently have changes in abundance, you can see that visually.

**Comment by jvhagey** [comment]
Hi Amy and Bryan,
Super excited to see plots are already in the works for this! I was looking to plot of the results of the differentialTest() function. In the mean time while graphing functions aren't ready for the differentialTest() output, to get an idea of the direction of the differences in abundance between groups can I just graph the taxa from list of differential abundance taxa using the raw count data from the otu_table() from the original phyloseq object? Not sure if there were transformed/normalized abundances that were being used within corncob that would be more appropriate for graph. Thanks for the feedback!

**Comment by bryandmartin** [comment]
Fixed in ff3e86d
