### ISSUE TITLE
Relative abundance flag?

### ISSUE THREAD

**Issue by jvhagey** [bryandmartin/corncob#22]
Hi Bryan,

Corncob takes absolute values and then converts counts to relative abundance within the corncob or differentialTest function correct? Is there an argument already or might I suggest an enhancement to flag that you are giving the corncob or the differentialTest function relative abundances rather than absolute? I was looking to filter out relatively low abundance organisms to speed up initial testing and double check things before I run all the ASVs. I can reduce the data set in other ways, just thought a flag for relative abundance would improve functionality. Thoughts? Looking forward to the paper!

Cheers,

**Comment by adw96** [comment]
Hi Jill! A key part of CORNCOB is that it needs absolute abundance information to know about the precision (sampling depth) of each sample. I can't picture how a relative abundance flag would work without needing to make some strong assumptions about preprocessing. We may triage this for now, but we are thinking about ways to use the same philosophy for metagenomic and metabolomic data, so you can expect more functionality for that soon!

Thanks for your feedback and sorry that we can't help you with this one today!
