### ISSUE TITLE
FDR correction of both DA and DV

### ISSUE THREAD

**Issue by gavinmdouglas** [bryandmartin/corncob#24]
Thanks for developing corncob, it seems like a great tool!

I noticed today that the FDR correction is for both the DA and DV p-values in ```differentialTest```. I was only interested in testing for DA in the particular analysis I was running and I realized I was being unnecessary stringent by correcting for the DV values as well. I think others will likely be confused by this as well so I thought I'd mention it in case it could be clarified for future releases!

Also, I would have thought since testing for DA and DV were totally different hypothesis tests that the p-values from these tests shouldn't be corrected together anyway (but that's likely something I'm just not understanding).

Thanks,

Gavin

**Comment by bryandmartin** [comment]
Hi Gavin,

Thanks for opening this issue. I'll be testing and pushing updated hypothesis testing code today. Once they are all done, I'll work them into `differentialTest` and fix the bug that you pointed out.

Thanks!
Bryan
