### ISSUE TITLE
Upgrading otu_to_taxonomy for improved plotting

### ISSUE THREAD

**Issue by jvhagey** [bryandmartin/corncob#35]
Hi @bryandmartin,

Thanks for making the new plotting function for differentialTest() it look great! Unfortunately since my ASVs have been assigned down to species and I didn't use taxa_glom the plots get taken up by a big long name. What if the otu_to_taxonomy function was changed to include an argument for what taxonomy level you want returned? 

I came up with this:
```
otu_to_taxonomy <- function(OTU, data, level) {
  if(missing(level)) {
    return(apply(tax_table(data)[OTU,], 1, function(x) {paste(stats::na.omit(x), collapse = '_')}))
  } else {
  return(apply(tax_table(data)[OTU,level], 1, function(x) {paste(stats::na.omit(x), collapse = '_')}))
  }
}
```
So the default would still have the same output that it currently does, but you could call specific taxonomy like this: 
```
>otu_to_taxonomy(OTU = da_analysis_sub$significant_taxa, data = ps_sub, level= c("Species","Genus"))
                                       ASV_682                                        ASV_429 
"Lachnospiraceae_Lachnospiraceae_AC2044_group"                "Lachnospiraceae_Acetatifactor" 
                                       ASV_460                                        ASV_164 
                             "Lachnospiraceae"               "Lachnospiraceae_Acetitomaculum" 
                                       ASV_472                                       ASV_1021 
                             "Lachnospiraceae"                              "Lachnospiraceae" 
```
To add this to the plotting functions I added level as an argument to lines 27 and 31 of the plot_differentialTest.R file. Like this:
```
plot.differentialTest <- function(x, level, ...) {
  signif_taxa <- x$significant_taxa
  if ("phyloseq" %in% class(x$data)) {
    if (!is.null(x$data@tax_table)) {
      signif_taxa <- otu_to_taxonomy(signif_taxa, x$data,level)
    }
  }
```
This really improved the legibility of my graph. Let me know what you think!

**Comment by bryandmartin** [comment]
Thanks, this is a great idea! I'll work on implementing it.

**Comment by jvhagey** [comment]
Hi @bryandmartin,

Since the change there is a minor hiccup with the plotting. If you call a higher level of taxa than what you used to run corncob you get overlapping points on the graph. Maybe plotting function would ideally throw out an error or people should just be aware and not try and do it. See example below. 

```
ps_sub_gen <- tax_glom(ps_sub, "Genus")
set.seed(1)
da_analysis_sub_gen <- differentialTest(formula = ~ Sample_Type, phi.formula = ~Sample_Type, formula_null = ~ 1, phi.formula_null = ~ 1, test = "Wald", boot = FALSE, data = ps_sub_gen, fdr_cutoff = 0.05)
plot(da_analysis_sub_gen,level=c("Family"))
```
Here is a screen shot of the overlapping:

![capture](https://user-images.githubusercontent.com/21023514/52246740-bb5d3300-289b-11e9-9acf-9305bec7023d.PNG)

**Comment by bryandmartin** [comment]
Hi @jvhagey ,

Thanks for noticing this. I added a fix now. If there is overlap, I add the unique OTU name identifier to the label. It should now be separated in the plot.
