### ISSUE TITLE
Error in installation (* creating vignettes ... ERROR)

### ISSUE THREAD

**Issue by gilsharon** [bryandmartin/corncob#37]
Hello, 
Probably a local issue, but figured it would be useful for others, in case they see the same. 
In trying to install CornCob and encountered an error in creating vignettes for whatever reason. 

```
* preparing ‘corncob’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Error: processing vignette 'corncob-intro.Rmd' failed with diagnostics:
Failed to compile corncob-intro.tex.
Execution halted
Installation failed: Command failed (1)
```
Installing TinyTex solved it.

> tinytex::install_tinytex()

**Comment by bryandmartin** [comment]
Hi @gilsharon ,

Thanks for posting this! Now if others encounter a similar issue and try to post it, this will come up in their search. I'm closing it as an open issue since it does not require any change to corncob.
