### ISSUE TITLE
option to define order of levels in bbmdl? 

### ISSUE THREAD

**Issue by gilsharon** [bryandmartin/corncob#45]
Hi @bryandmartin, 

This might be a redundant question - Is there a way to determine which level for a mapping variable is tested against the rest (i.e., control)? right now the model orders alphanumerically. 

Thanks,
Gil

**Comment by bryandmartin** [comment]
Hi @gilsharon ,

If I am understanding correctly, you have a variable with multiple experimental groupings, and you want to change the baseline level? 

If so, I believe you can change this by changing the order of the levels of your factor. [Here's a guide to this.](http://www.cookbook-r.com/Manipulating_data/Changing_the_order_of_levels_of_a_factor/)

Let me know if that helps,
Bryan

**Comment by gilsharon** [comment]
@bryandmartin 

Thanks! that works. Never realized I could do that on the mapping file.

**Comment by bryandmartin** [comment]
Great, thank you!
