### ISSUE TITLE
[question] how to get statistics for individual coefficients or contrasts

### ISSUE THREAD

**Issue by cdiener** [bryandmartin/corncob#46]
Hi,

I was browsing through the docs but could not find any information how I would go about getting the coefficients for several terms in `bbdml` or differential tests along with the associated test statistics and p value. 

For instance if my design would be `abundance ~ var1 + var2` how can I get the fitted coefficients for each variable or a particular contrast (for instance `coef1 + coef2`) similar to DESeq2 or voom?

Thanks!

**Comment by cdiener** [comment]
Okay, already found out that you can get the coefficients by accessing `da$all_models`.

**Comment by adw96** [comment]
@bryandmartin

**Comment by bryandmartin** [comment]
Hi @cdiener ,

Yes, `da$all_models` will return all the model summaries as a list for objects of class `differential_test`. For objects of class `bbdml`, you can just call summary, or specify a different hypothesis test using any of `lrtest`, `pbLRT`, `pbWald`, and/or `waldchisq`.
