### ISSUE TITLE
Vignette missing?

### ISSUE THREAD

**Issue by mikemc** [bryandmartin/corncob#47]
I just installed corncob, and the vignette seems to be missing / not rendered during the install
```
> library(corncob)
> browseVignettes(package = "corncob")
No vignettes found by browseVignettes(package = "corncob")
```

**Comment by bryandmartin** [comment]
Use the following code:

```# install.packages("devtools")
devtools::install_github("bryandmartin/corncob", build = TRUE)
library(corncob)
# Use this to view the vignette in the corncob HTML help
help(package = "corncob", help_type = "html")
# Use this to view the vignette as an isolated HTML file
utils::browseVignettes(package = "corncob")
```

Please re-open this issue if this does not solve your problem.

Thanks!
Bryan

**Comment by mikemc** [comment]
Thanks for your reply. That is what essentially what I did wrote above though, since `utils::browseVignettes(package = "corncob")` is the same as `browseVignettes(package = "corncob")`, so the effect is the same. The call to the help works, but the call for the Vignette fails.

**Comment by mikemc** [comment]
Thanks for your reply @bryandmartin. That is what essentially what I wrote above though, since `utils::browseVignettes(package = "corncob")` is the same as `browseVignettes(package = "corncob")` (the utils package is loaded when R starts), so the effect is the same when I run what you suggest. The call to the help works, but the call for the Vignette fails. If it helps, I'm using R version 3.5.3 on Linux.

I believe you need to reopen the issue.

**Comment by bryandmartin** [comment]
When you use `install_github()`, are you seeing something that says "* creating vignettes ... OK" in the text output? The install should pause on this line for a minute, because the vignette takes a minute or so to build.

**Comment by mikemc** [comment]
Ah, this is the problem I was having [here](https://github.com/r-lib/devtools/issues/1954). Installing with 
`devtools::install_github("bryandmartin/corncob", build = TRUE, build_opts = c())` fixes it.

**Comment by mikemc** [comment]
It sounds like this is due to a recent change in devtools / remotes (https://community.rstudio.com/t/vignettes-suddenly-stopped-installing/18391) (I'm using devtools 2.0.1)

**Comment by bryandmartin** [comment]
Thanks! A good reminder things updated when testing issues like this. It looks like they have plans to fix this, but in the meantime I'll update the README.

**Comment by patperu** [comment]
Hi,

`devtools::install_github` calls in fact the package `remotes`. 

Since version 2.1.0 `remotes::install_github` has a new argument `build_vignette`. 
So to build the vignette you should use
`remotes::install_github("bryandmartin/corncob", build_vignette = TRUE)`

Bye
Patrick
