### ISSUE TITLE
Curl error when trying to install package via install_github()

### ISSUE THREAD

**Issue by himelmallick** [bryandmartin/corncob#48]
I get this curl error when trying to install the package:
```r
devtools::install_github("bryandmartin/corncob")
```
```
Error in curl::curl_fetch_memory(url, handle = h) : 
Failed to connect to api.github.com port 443: Connection refused
```

**Comment by bryandmartin** [comment]
Hi @himelmallick ,

This is not an issue I'm familiar with, so we may need to troubleshoot here. Could you please try manually setting the host using:

```devtools::install_github("bryandmartin/corncob", host = "https://api.github.com")```

**Comment by himelmallick** [comment]
OK - seems like I am getting this issue with other Github R packages as well - so I will try to resolve this issue on my end to see if there is anything about my computer that is causing the issue - I am closing the issue for now. Thanks!
