### ISSUE TITLE
Interpreting Effect Sizes 

### ISSUE THREAD

**Issue by nearinj** [bryandmartin/corncob#64]
Hi Bryan,

Thanks for the work on the tool. I was wondering if you had any suggestions on how to interpret the effect sizes calculated from corncob. Are there any current guidelines for this?

I find that looking at effect sizes and significance tends to be more useful then significance alone, however, I'm not sure how to interpret the magnitude of the effect sizes reported by corncob's lot.differentialTest (I'm guessing its a plot of the coefficients of the model?) For instance if modelling height vs microbe abundance would a value of -0.02 indicate that for every unit increase in height, relative abundance of that microbe goes down by 0.02?

Thanks
Jacob Nearing

**Comment by nearinj** [comment]
Thanks Byan,

I will need to do some more reading to get a real feel for the coefficients from the model. As you suggested I will also look at some of the more interesting ASVs individually to get a better feel for how the groups are related!

**Comment by Midnighter** [comment]
I know it's an old issue but I was tripping over this one (it's somewhat related to my request in #113). I realize now that a log fold change is probably not feasible as it only makes sense when comparing two cases directly. I think a few words as you explain here would be a great addition to the vignette which at the moment only includes plots that show differential abundance but never mentions in what unit this is measured or how to interpret it.
