### ISSUE TITLE
Adding a contrasts argument

### ISSUE THREAD

**Issue by BrandonDKayser** [bryandmartin/corncob#68]
This is a great tool and I'm looking forward to using it.

Would there be a way to incorporate a contrast argument into `differentialTest`? This would be useful for testing the effects of levels within a factor, but would also facilitate repeated measures analyses. I was able to apply the "trick" for 2-way repeated measures data (group x condition) where group-specific condition effects are tested with subjects nested within groups, as described in the [DESeq2 User Guide](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#group-specific-condition-effects-individuals-nested-within-groups). However, contrast tests are necessary to determine whether the condition effect differs between groups. 

Perhaps if there was a way to extract the variance-covariance matrix for the regression coefficients in each model, then a Wald-test between different coefficients could be used, as [employed by DESeq2](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#contrasts-1).

**Comment by adw96** [comment]
Hey @bryandmartin -- @cdiener is requesting this feature too. You and I discussed this a while ago -- could you please prioritize?

**Comment by mworkentine** [comment]
Adding a vote for this - would be super helpful

**Comment by bryandmartin** [comment]
Hi all (@BrandonDKayser , @adw96 , @cdiener, @mworkentine ),

Thanks for all the interest in this feature! Just wanted to provide a brief update that this is now in active development, and I plan to make this the last major change to corncob before submitting the package to CRAN.

With that in mind, please let me know if there is any specific interfaces or usability you'd like to have regarding contrasts within corncob, and I'll do my best to make sure that they get incorporated.

Thanks @BrandonDKayser for the original feature request (and the rest of you for supporting it). Requests like these help make corncob as useful and user-friendly as possible!

Bryan

**Comment by BrandonDKayser** [comment]
Asking for more features in the easy part. Thank YOU for developing a statistically robust method for microbiome analysis. 

It would be ideal if you could mimic the LIMMA interfaces. Being able to specify contrasts as strings (e.g. `'trt = group_b - group_a'`) as well as matrices `rbind("avg" = c(-1/2, -1/2, 1/2, 1/2), "AvsD" = c(-1, 0, 0, -1))` would be desirable and probably speak to different audiences.

**Comment by mworkentine** [comment]
I agree with @BrandonDKayser - a couple of different levels of interfaces would be nice for different experience levels.  As mentioned, Limma, edgeR, and DESeq2, all have "easy" ways to specify contrasts but allow for more complicated designs through a contrast matrix.

**Comment by bryandmartin** [comment]
Thanks, that's exactly what I was looking for. I'll update this issue when the changes are live.

**Comment by cdiener** [comment]
Also agreeing with @BrandonDKayser and @mworkentine. The interfaces as used in limma or DESeq2 have usually been fine for us. Defining simple contrasts by strings and more complex ones by weight vectors seems the most useful.

**Comment by emarques1** [comment]
Hey @bryandmartin , has there been an update to this? I'm really interested in identifying which one of my groups are significantly different from each other. Thanks.

**Comment by bryandmartin** [comment]
Hi @emarques1 (et al.),

Thanks for your patience on this. As I mention in #79 , this feature request did (obviously) get tabled for a while when my workload got very high.

In full disclosure: the CRAN repository managers like new statistical software packages to point to a published methods paper. The `corncob` paper has been sitting in the "[Papers to Appear in Subsequent Issues](https://imstat.org/journals-and-publications/annals-of-applied-statistics/annals-of-applied-statistics-next-issues/)" of Annals of Applied Statistics for several months. I was initially waiting for it to get through so I could submit to CRAN including this feature request, and it's been sitting there so long it fell off my urgent to-do list.

Thanks for the push on this. I'll no longer be waiting for paper to go live to push major updates, and hope get this update going as soon as I can figure out an efficient way to program it. Apologies for the delay!

Bryan

**Comment by adw96** [comment]
Hi Bryan — I’m at CSU today and someone was saying that they really need a contrasts argument. Any updates on this? When can we expect a release? Thanks! Amy

**Comment by bryandmartin** [comment]
Hi all! (@BrandonDKayser , @adw96 , @cdiener, @mworkentine)

I'm pleased (and a little embarrassed) to announce that contrasts are now active in corncob! It required some major re-structuring, and a new core function `contrastsTest`, the contrast alternative to the formula implementation in `differentialTest`. 

This function is in beta, but is stable and working! I will be continuing to test it and update it. If you notice any issues with contrast implementation, or have any requests for enhancements or functionality, let me know in another issue! Now that the code base is implemented, it will be much easier to fine-tune and adjust, so it will be much quicker to update!

Closing this issue for now. 

Thanks all for your patience and understanding, I hope this function fits your needs!

**Comment by BrandonDKayser** [comment]
Thanks a bunch, Bryan. Looking forward to taking it for a ride!

**Comment by jessjarett** [comment]
Hi Bryan,
Is it best practice to first use differentialTest, then follow with the same model in contrastsTest, or just go directly
to contrastsTest with the comparisons of interest? Thanks for this new function!

**Comment by bryandmartin** [comment]
Hi @jessjarett ,

Sorry I missed this (please feel free to re-open an issue in the future). If you are specifically interested in testing a contrast, you can go straight to `contrastsTest`!
