### ISSUE TITLE
corncob and phyloseq objects: invalid class for otu_table

### ISSUE THREAD

**Issue by emilyjunkins** [bryandmartin/corncob#70]
Hello,

I have run corncob in both a unsubsetted and subsetted phyloseq object
`ps_WWTP`
`ps_subset2`

`ps_WWTP_RA = transform_sample_counts(ps_WWTP, function(x) x / sum(x))`
`ps_subset2_RA = transform_sample_counts(ps_subset2, function(x) x / sum(x))`

`data_phylum <- ps_subset2_RA %>%
    phyloseq::tax_glom("Phylum")`

`corncob <- bbdml(formula = OTU1 ~ 1,
                 phi.formula = ~ 1,
                 data = data_phylum)`

I received the following warning:
`Error in validObject(.Object) : invalid class “otu_table” object: 
 OTU abundance data must have non-zero dimensions.`

I thought this was due to the transformations as the class of the `otu_table` when from integer to double, even though R is supposed to handle them similarly. 

This also may be a phyloseq issue, but any info will help. Thanks!

**Comment by adw96** [comment]
Hi Emily -- corncob expects count data, and isn't appropriate for relative abundance data. I therefore suspect that

`corncob <- bbdml(formula = OTU1 ~ 1, phi.formula = ~ 1, data = ps_WWTP)`

and 

`corncob <- bbdml(formula = OTU1 ~ 1, phi.formula = ~ 1, data = ps_subset2)`

will work, but transforming the counts and then running corncob will not.

@bryandmartin Any chance we can run a check and add a more informative error message when folks pass in relative abundance data?

**Comment by emilyjunkins** [comment]
Hi Amy,

I originally ran what you suggested about and got the same error on my phyloseq objects, that's when I tried the transformation.

**Comment by bryandmartin** [comment]
Hi Emily,

What prints when you just type `ps_WWTP` into your R console?

**Comment by emilyjunkins** [comment]
`phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2974 taxa and 117 samples ]
sample_data() Sample Data:       [ 117 samples by 18 sample variables ]
tax_table()   Taxonomy Table:    [ 2974 taxa by 6 taxonomic ranks ]`

**Comment by bryandmartin** [comment]
Thanks!

Can you post the line of code you ran with `ps_WWTP`, along with the error message that came out, just so I can make sure I am understanding everything correctly?

I will second @adw96 about the RA data. That error does not surprise me.

**Comment by emilyjunkins** [comment]
I figured it out!

These are ASVs and I needed to use the ASV header in my phyloseq object (the ref seq), which isn't necessarily the same as a file I'd write out to store. Here my solution:

`corncob <- bbdml(formula = AGCAGCCGCGGTAATACGTAGGTGGCGAGCGTTGTCCGGAATTACTGGGTGTAAAGGGCGCGTAGGCGGGCGCTTAAGTCAGACGTGAAATACCGAGGCTCAACCTCGGGGCTGCGTTTGAAACTGGGCGTCTTGAGTGCCGGAGAGGGAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGA ~ 1,
                 phi.formula = ~ 1,
                 data = ps_WWTP)`


Is there a way to make this easier with ASV data since they aren't named with an OTU or ASV ID?

**Comment by bryandmartin** [comment]
Yes, I actually wrote a function specifically for this. Try this:

```
new_ps_WWTP <- clean_taxa_names(ps_WWTP)
corncob <- bbdml(formula = OTU1 ~ 1, phi.formula = ~ 1, data = new_ps_WWTP)
```

Please let me know if this works.

**Comment by emilyjunkins** [comment]
This is great, works perfectly on the original ps object.

Now, when I use the subsetted object generated from `decontam` and `phyloseq::subset_samples` and `phyloseq::subset_taxa`, I get the following error: 

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1919 taxa and 35 samples ]
sample_data() Sample Data:       [ 35 samples by 18 sample variables ]
tax_table()   Taxonomy Table:    [ 1919 taxa by 6 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 1919 tips and 1917 internal nodes ]

`new_ps_subset2 <- clean_taxa_names(ps_subset2)`

`data_phylum2 <- new_ps_subset2 %>% phyloseq::tax_glom("Phylum")`

`corncob2 <- bbdml(formula = OTU1 ~ 1, phi.formula = ~ 1, data = data_phylum2)`

`Error in trust::trust(objfun, parinit = theta.init, W = W, M = M, X = X.b,  : 
  parinit not all finite`

I has something to do with the `tax_glom` step bc when I run it at the ASV level, it works just fine.

Thanks for all of the feedback!

**Comment by bryandmartin** [comment]
Hi @emilyjunkins ,

I pushed an update (abba876) that I believe should solve this problem for good. Could you please try re-running `devtools::install_github("bryandmartin/corncob")`, completely closing and re-opening R, then re-running the command that was causing you issues?

Let me know if it still spits out an error or warning. At the very least, the message should now be more informative and coming through my software rather than the trust algorithm.

Thanks!
Bryan

**Comment by bryandmartin** [comment]
Closing this issue due to email follow up confirming that abba876 fixed this issue.
