### ISSUE TITLE
DifferentialTest giving on a subset of  samples gives "Error: $ operator is invalid for atomic vectors"

### ISSUE THREAD

**Issue by mestaki** [bryandmartin/corncob#73]
Hi @bryandmartin ,
Really enjoying Corncob so far! I'm running into the classic error that I can't figure out.
```
Error: $ operator is invalid for atomic vectors
```
Summary: I've got a phyloseq object with 4 groups across 2 time points (wk0,  wk6).
```
> ps
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2239 taxa and 63 samples ]
sample_data() Sample Data:       [ 63 samples by 34 sample variables ]
tax_table()   Taxonomy Table:    [ 2239 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 2239 tips and 2238 internal nodes ]
refseq()      DNAStringSet:      [ 2239 reference sequences ]
```
What I'm interested in is looking at each group's  change separately across time.
For example, I can successfully subset my phyloseq object like so:
```
> subset_samples(ps, na_removed_group=="VWR")
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2239 taxa and 12 samples ]
sample_data() Sample Data:       [ 12 samples by 34 sample variables ]
tax_table()   Taxonomy Table:    [ 2239 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 2239 tips and 2238 internal nodes ]
refseq()      DNAStringSet:      [ 2239 reference sequences ]
```
So, with corncob (0.1.0):
```
cc.VWR <- differentialTest(formula = ~ time,
                                  phi.formula = ~ time,
                                  formula_null = ~ 1,
                                  phi.formula_null = ~ 1,
                                  test = "Wald", boot = F,
                                  data = subset_samples(ps, na_removed_group=="VWR"),
                                  fdr_cutoff = 0.05)
#which gives me the error
Error: $ operator is invalid for atomic vectors
```
This problem only seems to occur with this particular group. Using the same formula but subsetting with any of the other 3 groups runs successfully without any errors. If I run the whole data set together, it also works just fine. There is nothing special about this VWR group as far as I can see.
Any thoughts?

**Comment by bryandmartin** [comment]
Hi @mestaki,

Thanks for posting the issue. This *was* a classic issue, but I believe I have squashed it for good in a previous update. 😀

Could you please try re-installing corncob using the prompt in the readme, closing and re-opening R to reset, and then running your code again? Let me know if you still have issue after this.

Bryan

**Comment by mestaki** [comment]
Thanks @bryandmartin , that was it! Re-installed and now works like magic :rabbit: :tophat:
