### ISSUE TITLE
(Possible) Vignette correction? 

### ISSUE THREAD

**Issue by JacobRPrice** [bryandmartin/corncob#75]
Under the heading "Analysis for Multiple Taxa", the second, third, and fourth paragraphs and the following code reads **(emphasis mine)**: 

> Next, we use the differentialTest command. We specify the covariates of our model using formula and phi.formula as before, except we no longer include the response term because we are testing multiple taxa. We also specify which covariates we want to test for by removing them in the formula_null and phi.formula_null arguments.  

> The difference between the formulas and the null version of the formulas will be the variables that are tested. In this case, as when we examined the single taxon, **we will be testing the coefficients of DayAmdmt for both the expected relative abundance and the overdispersion.** 

> We set fdr_cutoff to be our controlled false discovery rate. 

```
set.seed(1)
da_analysis <- differentialTest(formula = ~ DayAmdmt,
                                 phi.formula = ~ DayAmdmt,
                                 formula_null = ~ 1,
                                 phi.formula_null = ~ DayAmdmt,
                                 test = "Wald", boot = FALSE,
                                 data = soil,
                                 fdr_cutoff = 0.05)
```

If I'm reading this right, the code is testing for differential abundance across `DayAmdmt`, controlling for the effect of `DayAmdmt` on dispersion. If that's the case, I suggest correcting/updating the vignette.

**Comment by bryandmartin** [comment]
Hi @JacobRPrice ,

Thanks for pointing this out! Fortunately it's not a typo, but a poor use of English and bad clarity. I am referring to two different chunks of code in that paragraph. It's been cleaned up in ec35aeb.

Thanks for finding this!
Bryan
