### ISSUE TITLE
Filter for differential abundance

### ISSUE THREAD

**Issue by kunstner** [bryandmartin/corncob#78]
Hi,
is it possible to add a parameter to the _differentialTest()_ function to filter the 'effect size' as well? It would be advantageous to not just filter for fdr but for the effect as well (say _abs(effect) > 1_).
Best,
 Axel

**Comment by adw96** [comment]
I’m sorry but we’re not going to do that. You are welcome to sort/filter the taxa however you want after we have given you the output, but there are a number of problems with censoring the output by p-values or q-values. Let us know if you don’t know how to filter them yourself after the analysis is run and we can show you.
