### ISSUE TITLE
[question] how to get the covariance matrix from a corncob fit

### ISSUE THREAD

**Issue by cdiener** [bryandmartin/corncob#79]
Is it possible to obtain the coefficient covariance matrix from a `bbdml` or `differentialTests` output? To work around #68 I would like to run a Wald test for some vector `c` such that `H0: c*x = 0` which should be possible with the covariance matrix.

**Comment by bryandmartin** [comment]
Yes, this is possible!

If you take bbdml model output, you should be able to call `covMat <- chol2inv(chol(hessian(mod)))` to get the covariance matrix.

Thanks for the push on #68. It got tabled for a while (obviously) but I do still plan on completing it before CRAN submission after the publication is finally live!

**Comment by cdiener** [comment]
Thanks!
