### ISSUE TITLE
ERROR: compilation failed for package ‘lpSolveAPI’

### ISSUE THREAD

**Issue by Ivy-ops** [bryandmartin/corncob#86]
Hi developer, 
Thanks for creating this package. I met this error in package installation. May I know how to solve it? Your help is highly appreciated! Thanks!!

`* DONE (ROI)
* installing *source* package ‘lpSolveAPI’ ...
** package ‘lpSolveAPI’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/usr/local/biotools/r/R-3.6.2/lib64/R/include" -DNDEBUG -I../inst/include  -I/usr/local/biotools/r/R-3.6.2/R-dependencies/include  -fpic  -I/usr/local/biotools/r/R-3.6.2/R-dependencies/include -fPIC -I/usr/local/biotools/r/R-3.6.2/include  -c RlpSolve.c -o RlpSolve.o
gcc -I"/usr/local/biotools/r/R-3.6.2/lib64/R/include" -DNDEBUG -I../inst/include  -I/usr/local/biotools/r/R-3.6.2/R-dependencies/include  -fpic  -I/usr/local/biotools/r/R-3.6.2/R-dependencies/include -fPIC -I/usr/local/biotools/r/R-3.6.2/include  -c RlpSolveLink.c -o RlpSolveLink.o
RlpSolveLink.c: In function ‘RlpSolve_get_sensitivity_objex’:
RlpSolveLink.c:2043:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i = 0; i < ncol; i++) r[i] = NA_REAL;
   ^
RlpSolveLink.c:2043:3: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [RlpSolveLink.o] Error 1
ERROR: compilation failed for package ‘lpSolveAPI’
* removing ‘~/R/lpSolveAPI’
Error: Failed to install 'corncob' from GitHub:
  (converted from warning) installation of package ‘lpSolveAPI’ had non-zero exit status`

**Comment by bryandmartin** [comment]
Hi @Ivy-ops ,

So to start this actually isn't a problem with corncob. But I've dealt with issues like this a lot in the past so I'm happy to try and talk you through this. Let's start with a possible easy solution. Can you try entering

`install.packages("lpSolveAPI")` then try to install corncob again, and let me know if the error is the same?

**Comment by Ivy-ops** [comment]
Hi @bryandmartin,

Thanks for the nice help! Yes, the error is the same when install.packages("lpSolveAPI").

**Comment by bryandmartin** [comment]
Great! Before I close this, would you mind posting how you solved the issue in detail for posterity? I'm a bit confused why working on a cluster would cause this issue.
