### ISSUE TITLE
Error in `differentialTest` when phyloseq is not imported

### ISSUE THREAD

**Issue by mikemc** [bryandmartin/corncob#92]
The example in the docs for `differentialTest()` fails right now if phyloseq (and magrittr) aren't already loaded by the user. It seems that there is probably an internal call to `sample_data()` that needs to be prefixed with `phyloseq::`

    library(corncob)
    library(magrittr)

    data(soil_phylo)
    soil <- soil_phylo %>%
    phyloseq::subset_samples(DayAmdmt %in% c(11,21)) %>%
    phyloseq::tax_glom("Phylum")
    da_analysis <- differentialTest(formula = ~ DayAmdmt,
                                    phi.formula = ~ DayAmdmt,
                                    formula_null = ~ 1,
                                    phi.formula_null = ~ DayAmdmt,
                                    test = "Wald", boot = FALSE,
                                    data = soil,
                                    fdr_cutoff = 0.05)
    #> Error in sample_data(data): could not find function "sample_data"

<sup>Created on 2020-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bryandmartin** [comment]
Thanks for noticing this! I'll investigate. Should be easy enough to find.
