### ISSUE TITLE
possibly misguided question on controlling for certain factors with null formula

### ISSUE THREAD

**Issue by AstrobioMike** [bryandmartin/corncob#96]
Hey there, Bryan et al!

I have to of course start with saying i'm way out of my element here, so i apologize for what will likely be a completely unintelligible question despite my best efforts :)

Our general situation is that we want to test for differential abundance/variance between conditions on data that come from several different studies, and we want to try to take into account whatever signal/batch effect/whatever is introduced just due to the samples' source study. 

So maybe something like this:

|sample|condition|study|
|-------|---------|------|
| Sample_1 | healthy | Bryan_et_al |
| Sample_2 | healthy | Bryan_et_al |
| Sample_3 | sick | Bryan_et_al |
| Sample_4 | sick | Bryan_et_al |
| Sample_5 | sick | Bryan_et_al |
| Sample_6 | healthy | Rocks_et_al |
| Sample_7 | healthy | Rocks_et_al |
| Sample_8 | healthy | Rocks_et_al |
| Sample_9 | sick | Rocks_et_al |
| Sample_10 | sick | Rocks_et_al |

We're already where I have no idea if i'm using the correct terms or not, but my recent poking around trying to learn things I should already know tells me this might be called a random effect, which I think I could now figure out how to plug into an anova formula, but I don't think they can be explicitly provided to corncob currently.

However, it also seems like sometimes there is a workaround of sorts, as discussed in issue https://github.com/bryandmartin/corncob/issues/63, where it seems some process with an LRT and the proper null formula is able to accomplish something similar. But conceptually, i'm just not able to wrap my head around this yet.

My current attempt, based on that issue, this one https://github.com/bryandmartin/corncob/issues/72, and looking through your vignette, might be something like this to test for differential abundance based on condition, while trying to let the model take into account that some samples come from different studies:

```
da <- differentialTest(formula = ~ condition + study, 
                       formula_null = ~ study, 
                       phi.formula = ~ condition + study, 
                       phi.formula_null = ~ condition + study, 
                       data = phy_object, test = "LRT", boot = FALSE)
```

Would that do what I am talking about? And more importantly, is it sensible? 

Thanks! :) 
-Mike

**Comment by bryandmartin** [comment]
Hi @AstrobioMike ,

Thanks for patience on this. :)

Corncob does not currently allow for random effects. However, as you point out, I don't think they are necessary for this problem. Your code would test for an effect of condition on the mean abundance only, controlling for study, and controlling for the effect of both condition and study on the dispersion. This to me seems exactly like you want to test, and it is absolutely a sensible test.

Happy to answer follow up on this! Let me know if you have any before I close it.
Bryan

**Comment by AstrobioMike** [comment]
Awesome, thanks!!

**Comment by laracp** [comment]
Hi Mike and Bryan, 
Can I ask why you would use the LRT over the Wald test in this situation? 
Thanks!
Lara

**Comment by bryandmartin** [comment]
Hi @laracp ,

Practically speaking, the difference between LRT and Wald testing is negligible, with one notable exception: if you are testing across groups (e.g. differential abundance across experimental conditions) and one group has zero observed abundances for a taxa across all samples, then Wald testing will not be valid. This is accounted for in corncob by automatically removing those tests from output when Wald is specified, but it is still possible to test them using an LRT.

If you aren't in that setting, it really doesn't make much difference. Wald is more standard so I made that the default, but both are perfectly fine.

Hope this clears things up!
Bryan
