### ISSUE TITLE
waldchisq_test - silently fails when limma is missing

### ISSUE THREAD

**Issue by AdrianS85** [bryandmartin/corncob#98]
Dear Bryan,

I noticed that contrastTest was not giving me any results. After looking into the problem I noticed that waldchisq_test is interrupted at this line when limma is missing:

https://github.com/bryandmartin/corncob/blob/338323e9dfd303abe16ddcc582199f8028ccb14c/R/wald.R#L118

No indication that something went wrong is given. Hope it's relevant and helps!

Best
Adrian

**Comment by bryandmartin** [comment]
Thank you! This is very helpful. Can you please elaborate on what you mean by not giving any results?

**Comment by AdrianS85** [comment]
Of course, sorry : ] All p/p_fdr values returned by the functions were NA. This was not the case after installing limma.
