### ISSUE TITLE
corncob in CRAN or bioconductor

### ISSUE THREAD

**Issue by Russel88** [bryandmartin/corncob#99]
Hi

Are you considering submitting corncob to either CRAN or BioConductor? That would make it easier to add corncob as a dependency for other R packages. 

Thanks,
Jakob

**Comment by bryandmartin** [comment]
Hi @Russel88 ,

Thanks for your interest! Yes, we will put corncob on CRAN. I was originally going to wait for an update, but the update ended up slowing me down enough that I think it is worthwhile to push to CRAN and then update from there. Thanks for the push, I'll try to get to it this week.

Bryan

**Comment by bryandmartin** [comment]
Reopening this because it hasn't been accepted yet, just submitted! May take some back & forth, but corncob will be on CRAN in the *very* near future @Russel88 .

A genuine thank you for finally motivating me to do this.

**Comment by bryandmartin** [comment]
Whoops, forgot to close this! It's published now if you didn't already notice @Russel88 

https://CRAN.R-project.org/package=corncob
